application: azvd-webnotes
version: 1
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /notes
  script: notes.py

- url: /notes/.*
  script: notes.py

- url: /.*
  script: main.py
