application: azvd-webnotes
version: 1
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /notes
  script: notes.py

- url: /notes/.*
  script: notes.py

- url: /manifest
  static_files: manifest.cfm
  mime_type: text/cache-manifest
  upload: manifest.cfm

- url: /.*
  script: main.py
